name: Code Quality

on:
  push:
    branches-ignore: [ "main", "dev" ]

defaults:
  run:
    shell: bash

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          tools: composer
        env:
          runner: self-hosted
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Validate composer.json and composer.lock
        run: composer validate --strict
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Run PHP Lint
        run: composer run-script phplint
      - name: Run PHP_CodeSniffer
        run: composer run-script phpcs
      - name: Run PHPStan
        run: composer run-script phpstan
